### ISSUE TITLE
Maid Fiddler doesnt seem to work. 

### ISSUE THREAD

**Issue by Sai6969** [krypto5863/Legacy-Meido-s-Modular-Toolbox#1]
I installed LMMT today, all worked fine but after installing the Maid Fiddler, the game crashes when starting.

I searched around and found a few people in ulmf forum with the same issue, where one mentioned that the toolbox doesn't create a Managed folder in Sybaris, and thus the game crashes

**Comment by krypto5863** [comment]
Well, I've looked into this issue at length already and even with the correct process, making a managed folder and etc,. MaidFiddler still can crash your game at odd times. As a result, it seems to be a MaidFiddler bug.

**Comment by Sai6969** [comment]
Thank you for taking the time to fix it. Seems it wasn't a problem from either side, just a problem with Sybaris. I opened up Sybaris.ini and saw the Managed folder was redirected to Plugins/CM3D2x64 (or something similar, can't remember)/Managed. Just changing the path to Plugins/Managed fixes it. But this time I was in the BepInEx install, and not Sybaris one. I still haven't tried the Recommended Settings option as I fear the game will begin to crash again.

**Comment by krypto5863** [comment]
No even with proper procedure, MF is still known to cause crashes and issues. So beware it's usage. Anyways I'll be closing this issue now.
