### ISSUE TITLE
Autotranslate not work

### ISSUE THREAD

**Issue by ChrisWang99** [krypto5863/Legacy-Meido-s-Modular-Toolbox#2]
Hi, I installed LMMT as "Similar to Noctsoul's AIO" except Extra translation. I changed settings in autotranslatorplugin.ini, which proved to be useful in COM3D2. BUT nothing happend in CM3D2. The console says "The translation request was not completed before returning from translator" and the texture is still japanese. I'm confused.

My CM3D2 is ver1.66, and use nteals. Do you know what should I do next? Thanks a lot!

**Comment by ChrisWang99** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/32800408/166111247-01b38833-41e7-459d-93d7-e2f0b8e9904b.png">

**Comment by krypto5863** [comment]
If you change the default settings, I can't really help you. You can ask in the [XUnityAutoTranslator Repo](https://github.com/bbepis/XUnity.AutoTranslator) for help with Xuat itself though.
